name: pdf_reader
description: A Flutter app for reading PDF files.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.3.7
  pdfx: ^2.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
